# Test the scinode editor plugin using test
name: Test scinode editor blender plugin

on: [push]

env:
  TEST_IMAGE_NAME: ghcr.io/beautiful-atoms/beautiful-atoms

jobs:
  unittests:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        blender-version: ["3.2"]
    container:
      # env is not
      image: ghcr.io/beautiful-atoms/beautiful-atoms:blender${{ matrix.blender-version }}
      # Will need pytest installation
      options: --user root

    steps:
      - uses: actions/checkout@v2
      - name: Copy addons to blender
        run: |
          mkdir -p $BLENDER_PATH/scripts/addons_contrib
          cp -r scinode_editor $BLENDER_PATH/scripts/addons_contrib/
      - name: Enable blender addons
        # Enable the blender blender addon and save user pref
        run: |
          blender -b --python-exit-code 1 --python-expr  "import bpy; import addon_utils; addon_utils.enable('batoms', default_set=True); bpy.ops.wm.save_userpref(); print('success')"
          blender -b --python-exit-code 1 --python-expr  "import bpy; import addon_utils; addon_utils.enable('scinode_editor', default_set=True); bpy.ops.wm.save_userpref(); print('success')"
      - name: Test blender path
        # Test the sys.path contains the `addons_contrib` path
        run: |
          blender -b --python-exit-code 1 --python-expr "import sys; assert(any(['scripts/addons_contrib' in p for p in sys.path]))"
      - name: Test import batoms
        run: |
          blender -b --python-exit-code 1 --python-expr  "from batoms import Batoms; b = Batoms('O', ['O'], [[0, 0, 0]])"
      - name: Test import scinode_editor
        run: |
          blender -b --python-exit-code 1 --python-expr  "from scinode_editor.nodes.base_node import ScinodeTreeNode; n = ScinodeTreeNode()"
      - name: Install test dependencies
        run: |
          $BLENDERPY -m pip install pytest==6.2.5 pytest-blender
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
          mongodb-replica-set: test-rs
          mongodb-port: 27017
      - name: Test connect MongoDB
        run: |
          python -c "from scinode.database.client import scinodedb;data = list(scinodedb['daemon'].find({'name': 'localhost'}));print(data)"
      - name: Start daemon and setup database
        run: |
          scinode config setup --file tests/datas/config.json
          scinode daemon add --file tests/datas/daemon_localhost.json
          scinode daemon start localhost
      - name: Run blender unittests
        run: |
          cd tests
          pytest -svv
