# Test the bnodes plugin using test
name: Test bnodes blender plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TEST_IMAGE_NAME: ghcr.io/beautiful-atoms/beautiful-atoms

jobs:
  unittests:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Manually change these to match the blender image versions
        blender-version: ["3.0", "3.1", "3.2"]
    container:
      # env is not
      image: ghcr.io/beautiful-atoms/beautiful-atoms:blender${{ matrix.blender-version }}
      # Will need pytest installation
      options: --user root

    steps:
      - uses: actions/checkout@v2
      - name: Copy addons to blender
        run: |
          mkdir -p $BLENDER_PATH/scripts/addons_contrib
          cp -r scinode_editor $BLENDER_PATH/scripts/addons_contrib/
      # - name: Enable blender addons
      #   # Enable the blender blender addon and save user pref
      #   run: |
      #     blender -b --python-exit-code 1 --python-expr  "import bpy; import addon_utils; addon_utils.enable('batoms', default_set=True); bpy.ops.wm.save_userpref(); print('success')"
      #     blender -b --python-exit-code 1 --python-expr  "import bpy; import addon_utils; addon_utils.enable('Scinode Editor', default_set=True); bpy.ops.wm.save_userpref(); print('success')"
      # - name: Test blender path
      #   # Test the sys.path contains the `addons_contrib` path
      #   run: |
      #     blender -b --python-exit-code 1 --python-expr "import sys; assert(any(['scripts/addons_contrib' in p for p in sys.path]))"
      # - name: Test import batoms
      #   run: |
      #     blender -b --python-exit-code 1 --python-expr  "from batoms import Batoms; b = Batoms('O', ['O'], [[0, 0, 0]])"
      # - name: Test import scinode_editor
      #   run: |
      #     blender -b --python-exit-code 1 --python-expr  "from scinode_editor.node.base_node import BnodesTreeNode; n = BnodesTreeNode()"
      # - name: Install test dependencies
      #   run: |
      #     $BLENDERPY -m pip install pytest==6.2.5 flake8 pytest-blender
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --exclude=bnodes/node/,--exclude=bnodes/node_socket/,--exclude=bnodes/gui/,bnodes/ops/,bnodes/__init__.py --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --exclude=bnodes/node/,--exclude=bnodes/node_socket/,--exclude=bnodes/gui/,bnodes/ops/,bnodes/__init__.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # - name: Run blender unittests
      #   run: |
      #     cd tests
      #     pytest -svv
